version: '3.7'

services:
  web:
    build:
      context: ./
    command: bash ./start_server.sh
    volumes:
      - ./HealthMeters
    links:
      - db
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  migrate:
    build:
      context: ./
    command: python manage.py migrate
  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  db:
    image: "keinos/sqlite3"