version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./HealthMeters
    depends_on:
      - migrate
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  migrate:
      build: .
      command: python manage.py migrate --noinput
      volumes:
        - ./HealthMeters
      env_file:
        - ./.env.dev
  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf