# Generated by Django 3.0.8 on 2020-07-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('guid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('employees_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('guid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=36)),
                ('tg_username', models.CharField(max_length=36)),
                ('role', models.CharField(choices=[('manager', 'manager'), ('worker', 'worker')], max_length=36)),
                ('initials', models.CharField(max_length=36)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_to_company', to='general_module.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerToWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_to_worker', to='general_module.Employee')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_to_worker', to='general_module.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('guid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('employees_count', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_to_company', to='general_module.Company')),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data_to_employee', to='general_module.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='AdminPanelLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('activated', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_licence_to_company', to='general_module.Company')),
            ],
        ),
    ]
