# Generated by Django 3.0.8 on 2020-07-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
